### ISSUE TITLE
Warning about AbstractAMLTTPKS destructor

### ISSUE THREAD

**Issue by kashefy** [TWOEARS/blackboard-system#37]
Strange MATLAB warning I getting at the end of scripts:

> Warning: Cannot call delete method on object of class `AbstractAMLTTPKS` because the object cannot be updated. The object will be deleted using the default
> delete method.

Not sure how to get rid of it. I tried adding a delete method that doesn't do anything but still getting it. Any ideas?

**Comment by ivo--t** [comment]
sounds like you still might have had an "old" instantiateed object in workspace and changed the code inbetween. Possible?
