### ISSUE TITLE
HeadRotationKS and RotationKS

### ISSUE THREAD

**Issue by hagenw** [TWOEARS/blackboard-system#48]
We have at the moment the two knowledge sources `HeadRotationKS` and `RotationKS`, where `HeadRotationKS` seems to be the newer one.
@ningma97: Is `RotationKS` deprecated and can be removed?

**Comment by ningma97** [comment]
Yes. I left RotationKS there just in case it is needed by somebody (you;-p)

**Comment by hagenw** [comment]
Ok, I see ;)
I don't need it any longer and would propose to remove it, see #49

**Comment by ningma97** [comment]
and what about `ConfusionKS` and `ConfusionSolvingKS`? They are also deprecated and replaced by the new `LocalisationDecisionKS`

**Comment by hagenw** [comment]
Then I would propose to remove them as well. We can also do this in #49.
`ConfusionKS` and `ConfusionSolvingKS` are referenced at the moment in `blackboard_data/SourcesAzimuthsDistributionHypothesis.m`. Is this also obsolete?

**Comment by ningma97** [comment]
No it's not. The reference to `ConfusionKS` should be removed from `SourcesAzimuthsDistributionHypothesis`. I've done it.

**Comment by hagenw** [comment]
Ok, thanks.
