### ISSUE TITLE
Remove dependency on external GMTK tool

### ISSUE THREAD

**Issue by hagenw** [TWOEARS/blackboard-system#8]
We should implement `GmtkLocationKS` that it is purely based on Matlab internal functions and we can get rid of the GMTK dependency.

It might also be a solution to remove `GmtkLocationKS` if the other localisation knowledge sources are good enough.

/cc: @ningma97 @Hardcorehobel

**Comment by hagenw** [comment]
For problems with the current GMTK implementation see also https://dev.qu.tu-berlin.de/issues/1900

**Comment by ningma97** [comment]
I've added a GmmLocationKS that doesn't require GMTK in the blackboard and an example for showing its performance. Where should I put the trained models though?

**Comment by hagenw** [comment]
Cool, that was very fast :)

The learned models should be put in the internal database (I'm afraid it would still be a good idea if we could figure out how to make this work on your Mac). At the moment they are stored in this folder: https://dev.qu.tu-berlin.de/projects/twoears-database-internal/repository/revisions/master/show/learned_models/GmtkLocationKS

How large is the learned data? Maybe you can make it available to me and I will put it into the database.

**Comment by ningma97** [comment]
OK I've sent it to hagen.wierstorf@tu-berlin.de

Will have a better look at the git-media thing

**Comment by hagenw** [comment]
I have added the data and the new `GmmLocationKS` is integrated and working now. I have started a pull request where I will work on the complete removal of the old `GmtkLocationKS` which will be replaced by `GmmLocationKS`, see https://github.com/TWOEARS/blackboard-system/pull/11

**Comment by hagenw** [comment]
The new `GmmLocationKS` works very nice. I was also able to remove our dependency on GMTK completely.
Only the ability to retrain the model is not yet integrated, but this will be done soon and is independent of the task described here, so I will close this issue.
