### ISSUE TITLE
Remove AcousticCuesKS

### ISSUE THREAD

**Issue by hagenw** [TWOEARS/blackboard-system#9]
Is there a reason we have [`AcousticCuesKS`](https://github.com/TWOEARS/blackboard-system/blob/master/src/knowledge_sources/AcousticCuesKS.m)?
Or should it provide something different compared to `AuditoryFrontEndKS`?

**Comment by ningma97** [comment]
This is an old KS that should've been removed. I will do this.

**Comment by ningma97** [comment]
done.
